### ISSUE TITLE
Incorrect output

### ISSUE THREAD

**Issue by everclear** [celer/csg#1]
Hi, This looks very interesting, but it doesn't seem to work. The output is jumble of triangles. Could you confirm the code in the repo is correct. Thanks.

**Comment by celer** [comment]
I can't confirm it's correct beyond it seems to work for the few examples I've tried - you can checkout the unit tests to see what I tried. Can you post your code? I mostly transcribed code written Javascript and Java into golang, so it's likely there are errors.

**Comment by everclear** [comment]
I tried the output in Meshlab (which I don't normally use) and it worked. Turns out that it was 'Normal' not being it lowercase in the output that was causing the issue. Thanks for your time.
